{"success": false, "error": "Traceback (most recent call last):\n  File \"securify/__main__.py\", line 259, in main\n    contract = fix_pragma(contract)\n  File \"securify/__main__.py\", line 207, in fix_pragma\n    installed_version = compiler_version()\n  File \"/home/smartcontract/SmartContract/securify2-master/securify/solidity/solidity_ast_compiler.py\", line 43, in compiler_version\n    version = get_solc_version_string()\n  File \"/home/smartcontract/SmartContract/securify2-master/venv/lib/python3.7/site-packages/solc/main.py\", line 35, in get_solc_version_string\n    stdoutdata, stderrdata, command, proc = solc_wrapper(**kwargs)\n  File \"/home/smartcontract/SmartContract/securify2-master/venv/lib/python3.7/site-packages/solc/utils/string.py\", line 85, in inner\n    return force_obj_to_text(fn(*args, **kwargs))\n  File \"/home/smartcontract/SmartContract/securify2-master/venv/lib/python3.7/site-packages/solc/wrapper.py\", line 169, in solc_wrapper\n    stderr_data=stderrdata,\nsolc.exceptions.SolcError: An error occurred during execution\n> command: `solc --version`\n> return code: `126`\n> stderr:\n\n> stdout:\n/home/smartcontract/.solc-select/usr/bin/solc-runner: è¡ 10: /home/smartcontract/.solc-select/usr/bin/solc-v0.7.0: æéä¸å¤\n", "results": []}