{"success": true, "error": "", "results": [{"severity_name": "HIGH", "pattern_name": "External call in loop", "description": "If a single call in the loop fails or revers, it will cause all other calls to fail as well.", "type": "Violation", "contentline": 37, "charnumber": 13}, {"severity_name": "HIGH", "pattern_name": "Unhandled Exception", "description": "The return value of statements that may return error values must be explicitly checked.", "type": "Violation", "contentline": 37, "charnumber": 13}]}